id = "garasrumble"
state = "CANCELLED"
icon = "https://raw.githubusercontent.com/starshardstudio/emblems/main/custom/garasrumble.png"
languages = ["it", "en"]

################################################################################

[title.main]
it = "Garasrumble"
en = "Garasrumble"

[title.post]
it = "Un torneo a coppie di Rocket League Rissa!"
en = "A duos Rocket League Rumble tournament!"

[core.about.description]
it = "<p><dfn>Rocket League</dfn>. Immagino abbiate sentito tutti parlare del gioco in cui automobili giocano a calcio con una palla gigante…</p><p>Ha una modalità a mio parere molto sottovalutata: <i>Rissa</i>!</p><p>Fornisce periodicamente ai giocatori un potenziamento casuale tra gli undici disponibili, e gli permette di decidere quando usarlo.</p><p>In passato, l'ho giocata un sacco assieme ad un amico; ora voglio vedere come ve la cavate voi in un <b>torneo 2v2</b>: siete pronti?!"
en = "<p><dfn>Rocket League</dfn>. You should've heard of the game where cars play soccer with a giant metal ball…</p><p>I feel that one of its game modes is very underrated: <i>Rumble</i>!</p><p>It gives players a random power-up among a pool of 11, and allows them to decide when to use it.</p><p>In the past, me and a friend played it a lot; now, I want to see how well you all can play it in a <b>2v2 tournament</b>: are you ready?!"

[core.cancelled.description]
it = "Il giorno del torneo non si sono presentati sufficienti partecipanti perchè il torneo potesse svolgersi."
en = "Not enough partecipants showed up on the day of the tournament for the competition to take place."

[[screenshot]]
src = "https://i.imgur.com/uJahEi5.png"
it = "Un'auto nel menu principale."
en = "A car in the main menu."

[[screenshot]]
src = "https://i.imgur.com/WpfMCQv.png"
it = "Una macchina colpisce un pallone ala calcio di inizio."
en = "A car hits the ball at kickoff."

[[screenshot]]
src = "https://i.imgur.com/FXNGVX9.png"
it = "Steffo segna un gol utilizzando un magnete."
en = "Steffo scores a goal using a magnet."

################################################################################

[play]
"Steam" = "https://store.steampowered.com/app/252950/Rocket_League/"
"Epic Games" = "https://store.epicgames.com/en-US/p/rocket-league"
"PlayStation" = "https://store.playstation.com/en-us/product/UP2002-CUSA01163_00-ROCKETLEAGUENA01/"
"Xbox" = "https://store.xbox.com/en-US/Xbox-One/Games/Rocket-League/233becfb-c914-4ef4-9a73-398e8195f00a"
"Nintendo Switch" = "https://www.nintendo.com/store/products/rocket-league-switch/"

[join]
"Matrix" = "https://matrix.to/#/#sss-garasrumble:ryg.one"
"Telegram" = "https://t.me/+vUsso7AzGZAyMzQy"

################################################################################

[date]
update = 2023-05-19T03:26:00+02:00
start = 2023-05-04T21:00:00+02:00
end = 2023-05-04T22:00:00+02:00

################################################################################

[[placement]]
place = 1
name = "Steffo"
score = "-"
reward = 0
