id = "la-rivinkita"
state = "FINISHED"
icon = "https://raw.githubusercontent.com/starshardstudio/emblems/main/rendered/arrows-turn-right.png"
languages = ["it"]

################################################################################

[title.pre]
it = "<a href=\"/it/\">Star Shard Events</a> e <a href=\"https://www.ryg.one\">RYG</a> presentano"

[title.main]
it = "'A Rivinkita"

[title.post]
it = "Il derby di Dota che tutti stavano aspettando"

[core.about.description]
it = """ \
<p>Le due grandi squadre rivali della RYG, l'<a href="https://stratz.com/teams/8718182">Alazio</a> e i <a href="https://stratz.com/teams/8223567">DaVinki</a>, si scontreranno ancora una volta su <i><a href="https://www.dota2.com/home">Dota 2</a></i> in una serie commentata <b>alla meglio di 3</b>!</p> \
\
<div class="chapter-2"> \
<div class="panel"> \
<h4>Alazio</h4> \
<ul>
<li>Gimbaro</li>
<li>Viktya</li>
<li>Kappa</li>
<li>Mallllco</li>
<li>Spaggia</li>
</ul>
</div> \
<div class="panel"> \
<h4>DaVinki</h4> \
<ul>
<li>Fritz</li>
<li>Alleander</li>
<li>Life</li>
<li>Adry</li>
<li>Gattopardo</li>
</ul>
</div> \
<div class="panel"> \
<h4> \
Commentatori \
</h4> \
<ul> \
<li>Steffo</li> \
<li>Sensei</li> \
</ul> \
</div> \
</div> \
 \
<p>Chi vincerà?</p> \
"""

################################################################################

[[action]]
it = "Diventa un caster"
url = "https://t.me/@Steffo"

[[action]]
it = "Iscriviti come riserva"
url = "https://t.me/@Steffo"

################################################################################

[date]
update = 2023-05-22T03:04:00+02:00
start = 2023-05-25T21:00:00+02:00
end = 2023-05-25T23:30:00+02:00

################################################################################

[[placement]]
place = 1
name = "Gimbaro"
score = "2 wins"
reward = 150

[[placement]]
place = 1
name = "Mallllco"
score = "2 wins"
reward = 150

[[placement]]
place = 1
name = "Spaggia"
score = "2 wins"
reward = 150

[[placement]]
place = 1
name = "Viktya"
score = "2 wins"
reward = 150

[[placement]]
place = 1
name = "Kappa"
score = "2 wins"
reward = 150

[[placement]]
place = 2
name = "Alleander"
score = "0 wins"
reward = 100

[[placement]]
place = 2
name = "Adry"
score = "0 wins"
reward = 100

[[placement]]
place = 2
name = "Life"
score = "0 wins"
reward = 100

[[placement]]
place = 2
name = "Gattopardo"
score = "0 wins"
reward = 100

[[placement]]
place = 2
name = "xZefyr"
score = "0 wins"
reward = 100
