state = "ENDED"

################################################################################

[dates]
start      = 2023-04-20T21:00:00+02:00
end        = 2023-04-20T21:30:00+02:00
lastUpdate = 2023-04-23T03:49:01+02:00

################################################################################

[[player]]
place  = 1
name   = "Steffo"
score  = "-"
reward = 100

[[player]]
place  = 2
name   = "Nemesis"
score  = "14m 57s"
reward = 80
