state = "ENDED"
icon = "https://raw.githubusercontent.com/starshardstudio/emblems/main/rendered/cubes-stacked.png"
languages = ["it", "en"]

################################################################################

[title.main]
it = "Momento Tetro"
en = "Tetra Moment"

[title.post]
it = "Una grossa lobby su TETR.IO!"
en = "A big TETR.IO lobby!"

[core.about.description]
it = "<p>Questa settimana ho deciso di organizzare una piccola lobby di <dfn><a href=\"https://tetr.io/\">TETR.IO</a></dfn>, un <b>puzzle game competitivo</b> in cui bisogna impilare tetramini in modo da completare linee più efficientemente degli avversari.</p><p>Penso di aver trovato un setup per avere partite divertenti tra giocatori di qualsiasi livello di abilità, e volevo sperimentarlo insieme a voi!"
en = "<p>This week I decided to organize a small lobby in <dfn><a href=\"https://tetr.io/\">TETR.IO</a></dfn>, a <b>competitive puzzle game</b> where you have to stack tetrominos to complete lines more efficiently than your opponents.</p><p>I think I found a setup to have fun matches between players of all skill levels, and I wanted to try it out with you all!"

[[screenshot]]
src = "https://i.imgur.com/qZLqugd.png"
it = "Un giocatore cerca di ottenere un All Clear in una partita da solo."
en = "A player tries to get a All Clear in a solo game."

[[screenshot]]
src = "https://i.imgur.com/Nc6XRXF.png"
it = "60 giocatori si sfidano nella modalità Quick Play."
en = "60 players battle in a Quick Play match."

################################################################################

[play]
"TETR.IO" = "https://tetr.io/"

[join]
"Matrix" = "https://matrix.to/#/#sss-momento-tetro:ryg.one"
"Telegram" = "https://t.me/+xGeePCWZTcwxY2Iy"

################################################################################

[date]
start = 2023-04-20T21:00:00+02:00
end = 2023-04-20T21:30:00+02:00

################################################################################

[[player]]
place = 1
name = "Steffo"
score = "-"
reward = 100

[[player]]
place = 2
name = "Nemesis"
score = "14m 57s"
reward = 80
